version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    environment:
      - BUNDLE_PATH=/myapp/vendor/bundle
    depends_on:
      - db
  feature_spec:
    build:
      context: .
      dockerfile: ./feature_spec/environment/Dockerfile
    environment:
      TARGET_PROT: http
      TARGET_HOST: localhost:3000
