source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'capybara', '~> 2.12', require: false
gem 'rspec'
gem 'selenium-webdriver', require: false
gem 'site_prism', '>= 2.12', require: false
